on: [push, pull_request]

name: Continuous integration

jobs:
  build:
    name: Test ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-20.04 }
          - { target: x86_64-apple-darwin, os: macos-latest }
          - { target: x86_64-pc-windows-gnu, os: windows-latest }
          - { target: x86_64-unknown-linux-musl, os: ubuntu-20.04, use-cross: true }
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-20.04, use-cross: true }
          - { target: aarch64-apple-darwin, os: macos-latest, use-cross: true }
    env:
      BUILD_CMD: cargo

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@1.59.0
      with:
        targets: ${{ matrix.job.target }}

    - name: Install cross
      if: matrix.job.use-cross
      uses: taiki-e/install-action@v2
      with:
        tool: cross

    - name: Overwrite build command env variable
      if: matrix.job.use-cross
      shell: bash
      run: echo "BUILD_CMD=cross" >> $GITHUB_ENV

    - name: Opt Build
      shell: bash
      run: $BUILD_CMD build --release

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: target-${{ matrix.job.target }}
        path: target
        retention-days: 7
